"""Idea map operations: filtering, ranking, rendering, promotion."""

from __future__ import annotations

from .models import Idea, Project
from .store import Store, slugify


def rank(ideas: list[Idea]) -> list[Idea]:
    return sorted(ideas, key=lambda i: (-i.total, i.id))


def render_markdown(store: Store) -> str:
    data = store.load_idea_map()
    ideas = store.load_ideas()
    domains = store.domains()
    updated = data["meta"].get("updated", "")

    lines = [
        "# Idea Map",
        "",
        f"> Generated by `eros idea render` from `workspace/ideas/idea_map.yaml` — do not edit by hand.",
        f"> {len(ideas)} ideas · updated {updated} · scores are 1–5 per axis, total out of 25.",
        "",
        "**Axes:** Originality (O) · Technical Depth (D) · Interview Value (I) · "
        "Startup Potential (S) · Reuse (R)",
        "",
        "## Flagship candidates",
        "",
    ]
    flagships = [i for i in ideas if i.flagship_candidate]
    for idea in rank(flagships):
        lines.append(f"- **{idea.id} — {idea.title}** ({idea.total}/25): {idea.pitch}")

    lines += ["", "## Top 15 overall", "", "| # | ID | Idea | Domain | O | D | I | S | R | Total |",
              "|---|----|------|--------|---|---|---|---|---|-------|"]
    for n, idea in enumerate(rank(ideas)[:15], 1):
        s = idea.scores
        flag = " 🚩" if idea.flagship_candidate else ""
        lines.append(
            f"| {n} | {idea.id} | {idea.title}{flag} | {domains.get(idea.domain, idea.domain)} "
            f"| {s.originality} | {s.technical_depth} | {s.interview_value} "
            f"| {s.startup_potential} | {s.reuse} | **{idea.total}** |"
        )

    for key, name in domains.items():
        group = [i for i in ideas if i.domain == key]
        if not group:
            continue
        lines += ["", f"## {name} ({len(group)})", "",
                  "| ID | Idea | Pitch | O | D | I | S | R | Total |",
                  "|----|------|-------|---|---|---|---|---|-------|"]
        for idea in rank(group):
            s = idea.scores
            flag = " 🚩" if idea.flagship_candidate else ""
            status = " *(promoted)*" if idea.status == "promoted" else ""
            lines.append(
                f"| {idea.id} | **{idea.title}**{flag}{status} | {idea.pitch} "
                f"| {s.originality} | {s.technical_depth} | {s.interview_value} "
                f"| {s.startup_potential} | {s.reuse} | **{idea.total}** |"
            )
    lines.append("")
    return "\n".join(lines)


CHARTER_TEMPLATE = """\
# {title}

**Promoted from:** {idea_id} · **Domain:** {domain} · **Score:** {total}/25

## Pitch

{pitch}

## Goals

- <!-- what does "done" look like? edit before running `eros decompose` -->

## Success criteria

- <!-- measurable outcomes: benchmarks, demos, writeups -->

## Constraints

- Python-first; runs on a single Windows laptop without cloud infrastructure.
- Keep external dependencies minimal and justified.
"""


def promote(store: Store, idea_id: str) -> Project:
    idea = store.get_idea(idea_id)
    slug = slugify(idea.title)
    project = Project(slug=slug, idea_id=idea.id, title=idea.title)
    charter = CHARTER_TEMPLATE.format(
        title=idea.title,
        idea_id=idea.id,
        domain=store.domains().get(idea.domain, idea.domain),
        total=idea.total,
        pitch=idea.pitch,
    )
    store.create_project(project, charter)
    idea.status = "promoted"
    store.update_idea(idea)
    return project
